language: node_js
node_js:
  - stable
branches:
  only:
  - source
cache:
  directories:
    - node_modules
before_install:

install:
  - npm install
script:
  - hexo g
after_success:
  - cd ./public
  - git init
  - git config --global user.name "lewis617"
  - git config --global user.email "897473127@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
 global:
   - GH_REF: github.com/lewis617/lewis617.github.io.git
