language: node_js
node_js:
  - stable
branches:
  only:
    - source
cache:
  apt: true
  directories:
    - node_modules
script:
  - hexo generate
  - hexo deploy
before_install:
  - openssl aes-256-cbc -K $encrypted_2ce5281af250_key -iv $encrypted_2ce5281af250_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - cp ./ssh_config ~/.ssh/config
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - git config --global user.name 'tianke.lyq'
  - git config --global user.email 'tianke.lyq@alibaba-inc.com'
after_success:
  - node bd-zz-send.js
