# Header
menu:
  主页: /
  归档: /archives

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- notice
- category
- tag
- tagcloud
- archive
- recent_posts
- follow_me

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-88398388-1
gauges_analytics:
favicon: /css/images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

donate:
  enable: true
  text: 如果您觉得本文帮到了您，就打赏支持一下吧！
  wechat: http://i1.piimg.com/567571/846f2be76e14e60f.png
  alipay: http://i4.buimg.com/567571/c65bd960784a2000.jpg
